# Generated by Django 3.2.9 on 2021-11-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211112_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Gallery',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='level',
            new_name='year',
        ),
    ]
