# Generated by Django 3.2.9 on 2021-11-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_course_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.TextField(),
        ),
    ]
